### ISSUE TITLE
Rajouter une gallerie pour les fichiers

### ISSUE THREAD

**Issue by danielsum** [philippejadin/Mobilizator#2]
Pour moi tu pourrais utiliser El Finder, pas besoin de réinventer la roue ;-)

**Comment by philippejadin** [comment]
Il y a déjà une gallerie non? Si tu upload des photos, elles appraissent en gallerie.

Je l'ai fait comme cela afin d'avoir une future gestion des droits et un stockage propre, par groupe.

**Comment by danielsum** [comment]
Par gallery, je voulais dire une modal (type Fancybox)

-- 
Daniel Sum

On 24 novembre 2015 at 15:56:12, Phliippe Jadin (notifications@github.com) wrote:

Il y a déjà une gallerie non? Si tu upload des photos, elles appraissent en gallerie.

Je l'ai fait comme cela afin d'avoir une future gestion des droits et un stockage propre, par groupe.

**Comment by philippejadin** [comment]
Il y a, cliques sur une image ici :
http://participer.123piano.com/groups/236/files/gallery


Philippe Jadin


2015-11-24 16:00 GMT+01:00 Daniel Sum <notifications@github.com>:

**Comment by danielsum** [comment]
Ah oui ça devait être un petit bug passager alors quand je clique j'avais juste l'image qui s'ouvrait en lien direct
