### ISSUE TITLE
geolocalisation des personnes, actions et groupes

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/Mobilizator#34]
- Ajouter latitude, longitude, geocode_status sur les tables users, groups, actions
- Geocoder les adresses en tache de fond (laravel-geocoder), 5 toutes les minutes, mettre à jour le champ geocode status (0 = pas géocodé, 1 = géocodé, -10 erreur)
- Afficher sur une carte (leaflet) avec 3 sortes de marqueurs : 
  - les actions futures
  - les personnes
  - les groupes
- aide qui explique de ne pas mettre une adresse trop précise si on ne veut pas être précisément taggé sur une carte (par exemple mettre une rue sans numéro, ou une place proche, ou juste un code postal)

**Comment by danielsum** [comment]
est-ce vraiment nécessaire de géolocaliser les personnes ? est-ce que les groupes sont pas suffisants ?

**Comment by philippejadin** [comment]
je trouve que pour les personnes c'est intéressant, ça permet de savoir qui est "dans les parages". Bien entendu ce serait optionel (celui ne met rien dans le champ adresse de son profil n'apparait pas sur la carte, et il en aura plus que quelques uns qui ne voudront pas :-))

**Comment by danielsum** [comment]
P-e une case à cocher tout de même ?

--
Daniel Sum

**Comment by philippejadin** [comment]
ah oui, bon idée, je vais voir comment faire.

et aussi note pour plus tard, une liste des participants...

**Comment by philippejadin** [comment]
bon c'est en cours, en test bientôt sur participer.tac ;-)

**Comment by philippejadin** [comment]
Première version fonctionnelle en ligne et dans les derniers commits.

**Comment by philippejadin** [comment]
y compris pour la carte de chaque groupe.
