### ISSUE TITLE
Gestion multilingue

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/Mobilizator#36]
J'ai commencé une gestion multilingue (traduction de l'interface), mais je cherche un bon moyen de

- déterminer la langue de l'utilisateur
- la stocker dans son profil si il est connecté
- garder le tout dans des urls séparées ? (pour l'instant, il y a /fr et /nl dans un middleware proposé par ceci : https://github.com/mcamara/laravel-localization 

Peux-tu @danielsum y jeter un coup d'oeuil ou me conseiller sur la meilleure méthode?

(il ne s'agit pas de traduire les modèles hein, uniquement l'interface :-) )

**Comment by danielsum** [comment]
Coucou Julien, 

Pour ça j'utilise ça dans le middleware

            $preferedLocal = $request->getPreferredLanguage(["fr","nl"]); => determine la lang préféré de l'utilisateur suivant le navigateur

**Comment by danielsum** [comment]
On utilise un middleware custom et plus complexe pour définir la langue courante...

Mais en soit ce que tu dois checker c'est s'il y a un Cookie lang, et si pas => tu choppe la langue du navigateur du client puis tu stocke le cookie comme ça : 

$isBot = isset($_SERVER['HTTP_USER_AGENT']) && preg_match('/bot|crawl|slurp|spider/i', $_SERVER['HTTP_USER_AGENT']); // Check si c'est un robot (pas obligatoire pour participer)

        /**
         * If User has never been logged => it will be redirect to his local url
         */
        if(!$request->cookie('locale') && !$isBot)
        {
            $local = \App::getLocale();
            $preferedLocal = $request->getPreferredLanguage($this->languages);

           // si la langue du navigateur n'est pas la langue actuelle => on redirige
            if ($local !== $preferedLocal) {
                Session::put('locale', $preferedLocal);
                $url = $request->isSecure()? 'https://': 'http://'.\Config::get('app.locales.' . $preferedLocal . '.url');
                // Forever store preferred language
                return redirect($url.$request->getRequestUri(), 302)->withCookie(cookie()->forever('locale', Session::get('locale')));
            } else {
               // Si c'est la bonne => on stocke juste l'info 
               return $next($request)->withCookie(cookie()->forever('locale', $local));
            }
        }

**Comment by philippejadin** [comment]
Alors je propose : 

- si pas dans la session de l'utilisateur, prendre la getPreferredLanguage(["fr","nl"]); et la stocker dans la session
- stocker la langue préférée dans le profil utilisateur (bonus) si connecté
- proposer un menu de choix de locale avec une route locale/{locale} qui set aussi dans la session et les préférences utilisateurs

et enfin : pas d'url spécifique par locale, ça fout le boxon et comme il n'y a que l'interface qui est traduite ça vaut pas fort la peine (et tant pis pour les moteurs de recherche ?)

**Comment by danielsum** [comment]
oui c'est pas grave, une autre astuce intelligente c'est de la foutre en tant que sous-domaine

example : participer.toutautrechose.be ou participeren.hardbovenhard.be ;-).

T'auras moins de problème de langue et tu seras sure de la langue !

**Comment by danielsum** [comment]
Voilà, j'ai laissé les 2 possibilités => soit c'est un domaine url = une langue ou soit c'est un seul nom de domaine et alors il faut rajouter un param ?force_locale=fr ou nl.

Cela devra être discuté lors de votre réunion de mardi ;-)

**Comment by philippejadin** [comment]
C'est super et ça marche, merci!

**Comment by philippejadin** [comment]
Je pense qu'il faut aussi stocker dans la table user la langue choisie par la personne, car quand on envoi les notifications par mail, il n'y a pas de session, je suppose qu'il utilise la langue par défaut dans ce cas.

Je propose de l'ajouter aux préférecnes de l'utilisateur (c'est un json dans la table users avec accès depuis le modèle user)

**Comment by philippejadin** [comment]
je ferme aussi pour l'instant. Les notifications sont envoyées dans la langue principale de l'installation, c'est suffisant comme ça.
