### ISSUE TITLE
Traduction de carbon

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/Mobilizator#40]
pour une raison inconnue carbon ne s'adapte pas à la locale en cours

quand il écrit "il y a 3 jours" en néerlandais plutôt que "3 dagen geleden" etc...

**Comment by danielsum** [comment]
https://github.com/jenssegers/date

**Comment by danielsum** [comment]
Il se base sur la langue principale : 

Tu dois installer ça : https://github.com/jenssegers/date

 	 	 
 		
 
 

 	 	 		
Daniel
Sum
Creative Developer
 	 		
W	cherrypulp.com
M	daniel@cherrypulp.com
T	+32 485 66 25 69
 
 
 
_digital agency	Facebook	Twitter	LinkedIn
 
 
 
 	 	 

On 8 juin 2016 at 10:41:13, Philippe Jadin (notifications@github.com) wrote:

pour une raison inconnue carbon ne s'adapte pas à la locale en cours

quand il écrit "il y a 3 jours" en néerlandais plutôt que "3 dagen geleden" etc...

**Comment by philippejadin** [comment]
Cool merci! Comment faire pour que les modèles laravel l'utilisent? C'est transparent?

Dans une vue j'ai par exemple ceci : 

{{ $discussion->updated_at->diffForHumans() }}

je dois changer le code dans toutes les vues ?

**Comment by danielsum** [comment]
Je crois oui, le plus simple serait de faire un modifier dans ton modele
Discussion par example

**Comment by philippejadin** [comment]
Curieusement maintenant ça fonctionne, cfr. http://deelnemen.hartbovenhard.be/?force_locale=nl

Je ferme donc
