### ISSUE TITLE
draperstudio/laravel-service-provider non trouvé

### ISSUE THREAD

**Issue by zefredz** [philippejadin/Mobilizator#43]
Bonjour,

Lors de l'exécution de la commande composer install, j'ai l'erreur suivante :

[RuntimeException]                                                                                                
  Failed to clone https://github.com/DraperStudio/Laravel-Service-Provider.git via https, ssh protocols, aborting.  
  - https://github.com/DraperStudio/Laravel-Service-Provider.git                                                    
    Cloning into '/home/fminne/projects/cms/Mobilizator/vendor/draperstudio/laravel-service-provider'...            
    remote: Invalid username or password.                                                                           
    fatal: Authentication failed for 'https://github.com/DraperStudio/Laravel-Service-Provider.git/'                
  - git@github.com:DraperStudio/Laravel-Service-Provider.git                                                        
    Cloning into '/home/fminne/projects/cms/Mobilizator/vendor/draperstudio/laravel-service-provider'...            
    ERROR: Repository not found.                                                                                    
    fatal: Could not read from remote repository.                                                                   
                                                                                                                    
    Please make sure you have the correct access rights                                                             
    and the repository exists.  

Quand je me rends sur la page https://github.com/DraperStudio/Laravel-Service-Provider.git via mon navigateur, j'ai effectivement une erreur 404.

En faisant une recherche sur github ( https://github.com/search?q=laravel-service-provider ), il semble effectivement que ce projet a disparu. Il semble y avoir un fork ici https://github.com/christaggart/laravel-service-provider mais je ne suis pas certain qu'il soit à jour et/ou qu'il fonctionne correctement avec Mobilizator.

Avez-vous une solution ?

Merci d'avance,

    Frédéric

**Comment by zefredz** [comment]
Complément, une erreur était générée avant l'erreur signalée dans mon post précédent :

 - Installing draperstudio/laravel-service-provider (0.1.3)
    Downloading: Failed       
    Failed to download draperstudio/laravel-service-provider from dist: The "https://api.github.com/repos/DraperStudio/Laravel-Service-Provider/zipball/0696e8f46a8c0a1053b2b29bd5d09441b60d2c50" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source

**Comment by danielsum** [comment]
Coucou Fred, 

Oui le provider l'a supprimé de packagist ! :/

Une solution c'est de forker ça sur le projet mobilizator. Je compte faire un fork et le maintenir à jour de notre coté en agence. 

En attendant, je vais faire la mise à jour pour que cela ne pose pas de problème.

**Comment by zefredz** [comment]
OK, merci :)

**Comment by danielsum** [comment]
@philippejadin @zefredz , quelqu'un aurait encore la dépendance de DraperStudio Flash (qui se trouve dans vendor/draperstudio/laravel-flash) ? Je vois qu'il a été utilisé aussi dans le projet mais comme j'ai pas travaillé depuis longtemps sur le projet, je ne l'ai pas :/ => pourriez-vous me l'envoyer en Zip ? 

En soit, l'approche serait de mettre ces packages dans un autre dossier que vendor et de mettre les dépendances dans le composer.json comme ici : 

        "psr-4": {
            "App\\": "app/",
            "DraperStudio\\ServiceProvider\\": "workbench/laravel-service-provider/src/",
            "DraperStudio\\Taggable\\": "workbench/laravel-taggable/src/",
            "DraperStudio\\Flash\\": "workbench/laravel-flash/src/"
        }

Comme ça je peux réparer ça merci !

**Comment by danielsum** [comment]
Voilà, j'ai vu que Philippe a essayé de forké le projet aussi => j'ai sû avoir le paquet manquant :-)

J'ai fait la mise à jour =>, j'ai simplement copier les repos que j'ai mis dans le dossier workbench

@zefredz , tu peux lancer un composer update sur ta machine => si tu as une erreur avec les Providers => tu dois les commenter dans le fichier config/app.php avant de faire l'update.

**Comment by zefredz** [comment]
OK, plus d'erreur cette fois-ci, merci :)

**Comment by philippejadin** [comment]
Merci d'avoir été aussi efficaces les gars!

@danielsum tu as une idée pourquoi il a tout retiré de packagist? C'est assez rude comme décision.

**Comment by danielsum** [comment]
@philippejadin , hélas non... Je trouve aussi cela assez rude de sa part surtout que les licenses sont MIT. Quoiqu'il en soit, on a dans l'idée au sein de Co-Labs de mutualiser des packages dans ce style qu'on maintiendrait tous ensemble (package Back-End et Front-End aussi).

On a travaillé sur des composants qui pourrait être utile pour le projet mobilizator (comme gestion commentaires, Realtime event, elastic search, composants de formulaire pour le front-end etc.).

Est-ce que cela t'intéresserait d'en utiliser ? (ils sont en privés pour l'instant mais on va bientôt les releases en open-source après refactor). L'idée c'est de ne pas réinventer mais aussi de mutualiser la roue pour faire avancer différents projets :-).

Tchuuz

**Comment by philippejadin** [comment]
Ca pourrait bien être intéressant :-)

Là pour l'instant je recherche un package (qui n'existe pas à mon avis) qui permettrait de géolocaliser un modèle.
J'imagine un trait qui : 

- ajoute une latitude et longitude au modèle (+ status de géocodage) dans une migration
- géolocalise le modèle en fonction de ce qu'une fonction getAddress() retournerait
- fait le tout avec le scheduler
- permet de chercher des modèles proches (recherche par proximité)

On a fait un outil de ce genre pour le boulot ici : https://github.com/philippejadin/karto
Mais rien n'est sous forme de package ou trait...
