### ISSUE TITLE
Site en maintenance, nous revenons très vite!

### ISSUE THREAD

**Issue by yuri25** [philippejadin/Mobilizator#49]
Established .... I see on the home page:
Site en maintenance, nous revenons très vite!
Please help what is my mistake?

**Comment by philippejadin** [comment]
Can you try on the command line : 
php artisan up

The message means the site is in maintenance mode, so it should fix it :-)

**Comment by yuri25** [comment]
It helped, thank you very much!

**Comment by philippejadin** [comment]
You are welcome. Any feedback welcome, it is a work in progress project :-)
