### ISSUE TITLE
ical export

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/Mobilizator#5]
Fichier ical en export :
- pour chaque groupe
- pour tous les groupes
- pour tous les groupes d'un utilisateur (avec une url du genre /user/{id}/ical )

**Comment by danielsum** [comment]
Moi je ferai un hook pour pouvoir relier son compte Gmail, Facebook à la plate-forme.

A partir de là, tu peux ajouter directement un event sans devoir créer un lien ical, mais sinon, je peux le faire ! ;-)

**Comment by philippejadin** [comment]
C'est pas super important, c'est juste pour ceux qui veulent voir apparaitre l'agenda dans leur agenda (moi je trouve ça très pratique, j'ai tout l'agenda TAC dans mon google calendar). Comme un flux rss en gros... (un truc de geek :-))

**Comment by philippejadin** [comment]
L'export ical marche pour l'agenda général, c'est suffisant pour l'instant
